# Generated by Django 2.0 on 2020-06-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_level'),
    ]

    operations = [
    ]
