# Generated by Django 2.0 on 2020-06-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200609_2025'),
    ]

    operations = [
    ]
