# Generated by Django 2.0 on 2020-06-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200609_2111'),
    ]

    operations = [
    ]
